//
//  SAConstants.h
//  fansky
//
//  Created by Zzy on 6/17/15.
//  Copyright (c) 2015 Zzy. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const SA_APP_DOMAIN;

FOUNDATION_EXPORT NSString *const SA_API_BASE_HOST;
FOUNDATION_EXPORT NSString *const SA_API_COMSUMER_KEY;
FOUNDATION_EXPORT NSString *const SA_API_COMSUMER_SECRET;
FOUNDATION_EXPORT NSString *const SA_API_ACCESS_TOKEN_PATH;
FOUNDATION_EXPORT NSString *const SA_API_REQUEST_TOKEN_PATH;
FOUNDATION_EXPORT NSString *const SA_API_AUTHORIZE_PATH;
FOUNDATION_EXPORT NSString *const SA_API_AUTHORIZE_CALLBACK_URL;

FOUNDATION_EXPORT NSString *const SA_API_HOST;
FOUNDATION_EXPORT NSString *const SA_API_VERIFY_CREDENTIALS_PATH;
FOUNDATION_EXPORT NSString *const SA_API_ACCOUNT_NOTIFICATION_PATH;

FOUNDATION_EXPORT NSString *const SA_API_HOME_TIMELINE_PATH;
FOUNDATION_EXPORT NSString *const SA_API_USER_TIMELINE_PATH;
FOUNDATION_EXPORT NSString *const SA_API_UPDATE_STATUS_PATH;
FOUNDATION_EXPORT NSString *const SA_API_UPDATE_PHOTO_STATUS_PATH;
FOUNDATION_EXPORT NSString *const SA_API_USER_PHOTO_TIMELINE_PATH;
FOUNDATION_EXPORT NSString *const SA_API_DELETE_STATUS_PATH;
FOUNDATION_EXPORT NSString *const SA_API_MENTION_STATUS_PATH;

FOUNDATION_EXPORT NSString *const SA_API_USER_SHOW_PATH;
FOUNDATION_EXPORT NSString *const SA_API_FOLLOW_USER_PATH;
FOUNDATION_EXPORT NSString *const SA_API_UNFOLLOW_USER_PATH;
FOUNDATION_EXPORT NSString *const SA_API_USER_FRIEND_PATH;
FOUNDATION_EXPORT NSString *const SA_API_USER_FOLLOWER_PATH;

FOUNDATION_EXPORT NSString *const SA_API_CONVERSATION_LIST_PATH;
FOUNDATION_EXPORT NSString *const SA_API_CONVERSATION_PATH;
FOUNDATION_EXPORT NSString *const SA_API_SEND_NEW_MESSAGE_PATH;
